### ISSUE TITLE
Unzip problem

### ISSUE THREAD

**Issue by rml1997** [aws-samples/cicd-for-ecs-workshop-code#1]
When unzipping the lab files I got an error about it being an invalid zip file. Downloaded it locally and unzipped it in windows fine, and uploaded the unzipped folder to get it working. I seemed to have the same issue with a zip downloaded from this github repo, so not sure if it is the version of unzip that is at fault. I'm in a bit of a rush for a job interview tomorrow or this report would be a bit better. Sorry!

**Comment by rizblie** [comment]
Not sure why you are having zip issues. However, please note that as of this weekend, the workshop has been changed so that the workshop files are now cloned directly from github, so this should help you avoid any zip issues.

See https://cicd-for-ecs.workshop.aws/en/3-setup/01-tools_resources.html#4-download-workshop-resources.

**Note:** There has been a major update of the workshop guide over the weekend. If you were mid-way through the workshop you may find that the workshop guide does not always align with the workshop-files.zip from the old version.
